# Generated by Django 4.2.5 on 2023-09-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stu')),
            ],
        ),
    ]
