# Generated by Django 4.2.5 on 2023-09-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_people'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
    ]
